# Generated by Django 2.0.2 on 2018-08-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skywalker', '0004_auto_20180808_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(default='Indefinida', max_length=50),
        ),
        migrations.AlterField(
            model_name='turma',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Idioma',
        ),
    ]
