# Generated by Django 2.0.2 on 2018-08-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skywalker', '0007_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matriculado',
            field=models.BooleanField(default=False),
        ),
    ]
