# Generated by Django 2.0.2 on 2018-08-09 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skywalker', '0008_user_matriculado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='language',
            new_name='idioma',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='finalizada',
        ),
    ]
