# Generated by Django 2.0.2 on 2018-08-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skywalker', '0009_auto_20180809_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.CharField(default='Indefinida', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='siap',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
